run:
  deadline: 5m
linters:
  disable-all: true
  govet:
    enable:
      - fieldalignment
  enable:
    - deadcode
    - errcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - typecheck
    - govet
    - staticcheck
    - ineffassign
    - deadcode
    - stylecheck
    - unconvert
    - goconst
    - misspell
    - gocyclo
    - gofmt
    - gosec
    - golint
    - bodyclose
    - depguard
    - errorlint
    - prealloc
    - whitespace
    - goerr113
